### ISSUE TITLE
Tidy up plugin declarations in build,gradle.kts files

### ISSUE THREAD

**Issue by atick-faisal** [atick-faisal/Jetpack-Compose-Starter#277]
Custom plugins can be defined in the libs.versions.toml file like this:
``` toml
# Plugins defined by this project
nowinandroid-android-application = { id = "nowinandroid.android.application" }
nowinandroid-android-application-compose = { id = "nowinandroid.android.application.compose" }
```
